# Generated by Django 5.0.1 on 2024-01-19 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logo/')),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_permit', models.FileField(blank=True, null=True, upload_to='business_permit/')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='product_cover_image/')),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_details', models.TextField(blank=True, null=True)),
                ('product_detail_image_1', models.ImageField(blank=True, null=True, upload_to='product_detail_image/')),
                ('product_detail_image_2', models.ImageField(blank=True, null=True, upload_to='product_detail_image/')),
                ('product_detail_image_3', models.ImageField(blank=True, null=True, upload_to='product_detail_image/')),
                ('product_detail_image_4', models.ImageField(blank=True, null=True, upload_to='product_detail_image/')),
                ('product_detail_image_5', models.ImageField(blank=True, null=True, upload_to='product_detail_image/')),
                ('product_image_color_1', models.ImageField(blank=True, null=True, upload_to='product_image_color/')),
                ('product_image_color_2', models.ImageField(blank=True, null=True, upload_to='product_image_color/')),
                ('product_image_color_3', models.ImageField(blank=True, null=True, upload_to='product_image_color/')),
                ('product_image_color_4', models.ImageField(blank=True, null=True, upload_to='product_image_color/')),
                ('product_sizechart_image', models.ImageField(blank=True, null=True, upload_to='product_sizeChart/')),
                ('product_category', models.CharField(blank=True, choices=[('ACCESSORIES', [('clothes', 'Clothes'), ('shoes', 'Shoes'), ('jewelry', 'Jewelry'), ('handbags', 'Handbags'), ('fancy', 'Fancy'), ('fragnance', 'Fragnance')]), ('BEAUTY_PRODUCTS', [('skincare', 'Skincare'), ('makeup', 'Makeup'), ('haircare', 'Haircare'), ('nailcare', 'Nailcare')])], max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('vendoruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='vendors_orders_discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('discounted_price', models.CharField(blank=True, max_length=50, null=True)),
                ('limitations', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVendor.vendors_product')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
