# Generated by Django 5.0.1 on 2024-01-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVendor', '0002_vendors_product_product_name_vendors_orders_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors_product',
            name='available_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
