# Generated by Django 5.0.1 on 2024-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVendor', '0003_vendors_product_available_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors_orders_discount',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
